apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ntfy.fullname" . }}
  labels:
    {{- include "ntfy.labels" . | nindent 4 }}
data:
  server.yml: |
    base-url: https://ntfy.localhome.com
    cache-file: /var/cache/ntfy/cache.db
    attachment-cache-dir: /var/cache/ntfy/attachments
    auth-file: /var/cache/ntfy/user.db
    auth-default-access: "read-write"
    listen-http: ":80"
