imagePullSecrets:
    regcred:
        username: ENC[AES256_GCM,data:33PchOuwlO/O/g==,iv:iVh/7qHZebxKKfw7usnRyIuScV9mtmZ9Yz/RckIzwuA=,tag:GANAYGF8/q/xNiAqva5CgA==,type:str]
        password: ENC[AES256_GCM,data:cE5Te0HBJkFl/F7gSHtl/BERzfmVqAMpY2j8xm1EHrMpjd8Z,iv:cHer824bSsz7gNmT6g9I6QThqYaI3lkhtakfMnuPGWA=,tag:hpZ+xbOjfkctv2lH/u/OcA==,type:str]
        email: ENC[AES256_GCM,data:RrwMsvjM0Lb1ZiJ2t8eTIRNQ0EM=,iv:jYWerwbxpK2UKZONLmde0Z04vmqXFYHaiBYOfYcwaB4=,tag:Ja85fSro4cXkrjNGyzk3sQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jsd2g7m3vkh629cged87fvvetsuzv8dalkv38ykpqmyqrkpqmymsr62hqr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzclYxcHB2U1Q2TGFsemoy
            M3Z2VXpIZ05oMjB3UEVaK3pXZEdYSVVuUzJrCkZ2RWhoQitVdWtqQ1AvVnUyZCtH
            U3p2VTdqdE5iK2EzQk1vNENmMXZFcTQKLS0tIFVhak95UjVJbk16WmVJNHVweUJJ
            bUtQVWRhQWc5NjROR3lDdFJQcEc4WmMKq44ATsoK20TJ43CYgE0rYnRXH68bSBRX
            ulPrPjBflI64EvG07gq57LYkY5pbhKHz5jFIRfjMH7FBFXyW9wDyeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-05T22:23:19Z"
    mac: ENC[AES256_GCM,data:nTxeM3a8r+TNDdYfoMLvt4wYLvxL+qqVg73yya7vBKmyLaIqbuJm9KI4hx7KJV8DJOkSEdIrrb6acMT65vfN0tx3Svl1bhAmCzEThJLcueeuvVZvXQNmShpXdYmF/2V9y1fb634UyamziRMJklxgZCUXdkQBs+Nz7TQqvs7sENs=,iv:gN1RNkNmEdfkISg8xNfubqUj5xHfM+1zvvrDfQPt658=,tag:yZzdw8vySUmyU1TCqqQFtg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|token|username|password|email)$
    version: 3.9.0
