apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "prowlarr.fullname" . }}
  labels:
    app: {{ include "prowlarr.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "prowlarr.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "prowlarr.name" . }}
    spec:
      initContainers:
        {{- include "common.restore.initContainer" (dict "Values" .Values "AppName" "prowlarr" "ConfigPath" "/config") | nindent 8 }}
      containers:
        - name: prowlarr
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.webuiPort }}
          env:
            - name: PUID
              value: "{{ .Values.env.PUID }}"
            - name: PGID
              value: "{{ .Values.env.PGID }}"
            - name: TZ
              value: "{{ .Values.env.TZ }}"
          volumeMounts:
            - name: config
              mountPath: /config
            {{- if .Values.persistence.restore.enabled }}
            - name: {{ if eq .Values.persistence.restore.existingClaim .Values.persistence.backup.existingClaim }}backup{{ else }}restore{{ end }}
              mountPath: {{ .Values.persistence.restore.mountPath }}
              {{- if .Values.persistence.restore.readOnly }}
              readOnly: true
              {{- end }}
            {{- end }}
            {{- if .Values.persistence.backup.enabled }}
            - name: backup
              mountPath: {{ .Values.persistence.backup.mountPath }}
              {{- if .Values.persistence.backup.readOnly }}
              readOnly: true
              {{- end }}
            {{- end }}
        {{- include "common.backup.sidecar" (dict "Values" .Values "AppName" "prowlarr" "ConfigPath" "/config") | nindent 8 }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.data.existingClaim }}
        - name: config
        {{- if eq .Values.persistence.config.type "emptyDir" }}
          emptyDir: {}
        {{- else }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.config.existingClaim }}
        {{- end }}
        {{- if and .Values.persistence.restore.enabled (ne .Values.persistence.restore.existingClaim .Values.persistence.backup.existingClaim) }}
        - name: restore
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.restore.existingClaim }}
        {{- end }}
        {{- if .Values.persistence.backup.enabled }}
        - name: backup
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.backup.existingClaim }}
        {{- end }}
