{{- if .Values.imagePullSecrets.regcred.username }}
apiVersion: v1
kind: Secret
metadata:
  name: regcred
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"https://index.docker.io/v1/\":{\"auth\":\"%s\"}}}" (printf "%s:%s" .Values.imagePullSecrets.regcred.username .Values.imagePullSecrets.regcred.password | b64enc) | b64enc }}
{{- end }}
